//name: Muhammad Nuhsyah Putra Bin Ramlee
//adminNumber:2045302
//class:DIT/FT/1B02
const db=require('./databaseConfig');
var category={  
    addCategory: function (catname,description, callback) { //userid is autogenerated
    var conn = db.getConnection();
    conn.connect(function (err) {
        if (err) {
            console.log(err);
            return callback(err,null);
        } else {
            console.log("Connected!");
            var sql = 'Insert into category(catname,description) values(?,?)';
            conn.query(sql, [catname,description], function (err, result) { 
                if (err) {
                    console.log(err);
                    return callback(err,null);
                }
                  conn.end();
                        if (err) {
                            console.log(err);
                            return callback(err,null);
                        } else {
                            console.log(result.null); 
                            return callback(null,result);
                        }
                    });
                }
            });

        },
        updatecategory: function (newCatname, newDescription, categoryid, callback) {
            var conn = db.getConnection(); 
            conn.connect(function (err) {
                if (err) {
                    console.log(err);
                    return callback(err,null);
                } else {
                    console.log("Connected!");
                    var sql = 'SELECT catname, description  FROM category WHERE categoryid = ?;';
                    conn.query(sql, [categoryid], function (err, result) {
                        if (err) {
                            console.log(err);
                            return callback(err,null);
                        } else {
    
                            if (!newCatname) newCatname = result[0].catname;
                            if (!newDescription) newDescription = result[0].description;
    
                            sql = 'UPDATE category SET catname = ?, description = ? WHERE categoryid = ?;'; // note 3 question marks
                            conn.query(sql, [newCatname, newDescription, categoryid], function (err, result) { // note 3 variables in the array []
                                conn.end();
                                if (err) {
                                    console.log(err);
                                    return callback(err,null);
                                } else {
                                    console.log(result); // affectedRows is built-in variable located in result object from the insert query
                                    return callback(null,result.affectedRows);
                                }
                            });
                        }
                    });
                }
            });
        }
    }

    





module.exports=category;