//name: Muhammad Nuhsyah Putra Bin Ramlee
//adminNumber:2045302
//class:DIT/FT/1B02
const db = require('./databaseConfig');
var game = {
    addgame: function (title, description, price, platform, fk_categoryid,year,img, callback) { //userid is autogenerated
        var conn = db.getConnection();
        conn.connect(function (err) {
            if (err) {
                console.log(err);
                return callback(err, null);
            } else {
                console.log("Connected!");
                var sql = 'Insert into game(title,description,price,platform,fk_categoryid,year,img) values(?,?,?,?,?,?,?)';
                conn.query(sql, [title, description, price, platform, fk_categoryid,year,img], function (err, result) {
                    conn.end();
                    if (err) {
                        console.log(err);
                        return callback(err, null);
                    } else {
                        console.log(result.insertId); // affectedRows is built-in variable located in result object from the insert query
                        // return callback(null,`Record ${result.insertId} is inserted`);
                        return callback(null, result.insertId);
                    }
                });
            }
        });
    },

    retrievegame: function (platform, callback) {
        var conn = db.getConnection();
        conn.connect(function (err) {
            if (err) {
                console.log(err);
                return callback(err, null);
            } else {
                var sql = `Select g.gameid ,g.title,g.description,g.price, g.platform,c.categoryid, c.catname, g.year, g.created_at
                From game g, category c 
                Where platform= ? and fk_categoryid = categoryid`;
                conn.query(sql, [platform], function (err, result) {
                    conn.end();
                    if (err) {
                        return callback(err, null);
                    } else {
                        return callback(null, result);
                    }
                });
            }
        });
    },

    deletegame: function (gameid, callback) {
        var conn = db.getConnection();
        conn.connect(function (err) {
            if (err) {
                console.log(err);
                return callback(err, null);
            } else {
                console.log("Connected!");
                var sql = 'Delete from game where gameid=?';
                conn.query(sql, [gameid], function (err, result) {
                    conn.end();
                    if (err) {
                        console.log(err);
                        return callback(err, null);
                    } else {
                        return callback(null, result.affectedRows);
                    }
                });
            }
        });
    },
    updategame: function (newtitle, newdescription, newprice, newplatform, newyear, fk_categoryid, id, callback) {
        var conn = db.getConnection();
        conn.connect(function (err) {
            if (err) {
                console.log(err);
                return callback(err, null);
            } else {
                console.log("Connected!");
                var sql = 'SELECT title, description,price,platform,year,fk_categoryid FROM game WHERE gameid = ?;';
                conn.query(sql, [id], function (err, result) {
                    if (err) {
                        console.log(err);
                        return callback(err, null);
                    } else {

                        if (!newtitle) newtitle = result[0].title;
                        if (!newdescription) newdescription = result[0].description;
                        if (!newprice) newprice = result[0].price;
                        if (!newplatform) newplatform = result[0].platform;
                        if (!newyear) newyear = result[0].year;
                        if(!fk_categoryid)fk_categoryid=result[0].fk_categoryid;

                        sql = 'UPDATE game SET title = ?, description = ?,price=?,platform=?,year=?,fk_categoryid=? WHERE gameid = ?;'; 
                        conn.query(sql, [newtitle, newdescription, newprice, newplatform, newyear, id, fk_categoryid], function (err, result) { 
                            conn.end();
                            if (err) {
                                console.log(err);
                                return callback(err, null);
                            } else {
                                console.log(result); // affectedRows is built-in variable located in result object from the insert query
                                return callback(null, result.affectedRows);
                            }
                        });
                    }
                });
            }
        });
    }
}
game.findAll = function(callback) {
    var dbConn = db.getConnection();
    dbConn.connect(function (err) {
        if (err) {//database connection gt issue!
            console.log(err);
            callback(err, null);
        } else {
            const findAllUsersQuery = "SELECT * FROM game;";
            dbConn.query(findAllUsersQuery, (error, results) => {
                dbConn.end();
                if (error) {
                    callback(error, null);
                } else {
                    callback(null, results);
                }
            });
        }
    });
},
game.SearchGame = function(name, callback){
    var dbConn = db.getConnection();
    dbConn.connect(function (err) {
        if (err) {//database connection gt issue!
            console.log(err);
            callback(err, null);
        } else {
            const findGameQuery = `"SELECT * FROM game WHERE LIKE '%${name}%'`;
            dbConn.query(findGameQuery,[name],(error, results) => {
                dbConn.end();
                if (error) {
                    callback(error, null);
                } else {
                    callback(null, results);
                }
            });
        }
    }); 
},
game.SearchFee = function(fee, callback){
    var dbConn = db.getConnection();
    dbConn.connect(function (err) {
        if (err) {//database connection gt issue!
            console.log(err);
            callback(err, null);
        } else {
            const findGameFeeQuery = `"SELECT * FROM game WHERE price <= '${fee}' `;
            dbConn.query(findGameFeeQuery,[fee],(error, results) => {
                dbConn.end();
                if (error) {
                    callback(error, null);
                } else {
                    callback(null, results);
                }
            });
        }
    }); 
},
game.Review = function(id,callback){
    var dbConn = db.getConnection();
    dbConn.connect(function (err) {
        if (err) {//database connection gt issue!
            console.log(err);
            callback(err, null);
        } else {
            const review = "SELECT * FROM game WHERE gameid = ?;";
            dbConn.query(review,[id],(error, results) => {
                dbConn.end();
                if (error) {
                    callback(error, null);
                } else {
                    callback(null, results);
                }
            });
        }
    }); 
}


module.exports = game;

